### ISSUE TITLE
EDTFDate.precision - question

### ISSUE THREAD

**Issue by sdreher** [ixc/python-edtf#1]
Hi - 

Great work on the python-edtf implementation. I'm hoping to use and contribute to this project for a larger application that stores fragmentary and ambiguous dates. 

Can you explain your thinking around the EDTFDate.precision function? I do have some confusion around what's being defined as "precision".
* Given an EDTF format of 14uu, the precision returns PRECISION_YEAR. I would expect it to return PRECISION_CENTURY, as only the century is specified.
* Given an EDTF format of 146u, the precision returns PRECISION_YEAR. I would expect it to return PRECISION_DECADE, as only the decade is specified.

Thanks in advance!

**Comment by cogat** [comment]
@sdreher thanks for raising this - I've seen you closed the issue but wanted to note the answer for record:

According to https://www.loc.gov/standards/datetime/pre-submission.html#unspecified , "14uu" means "some unspecified year in the 1400s" - so it is year precision (just not specific about which one). To specify the century, you'd use [14xx](https://www.loc.gov/standards/datetime/pre-submission.html#maskedprecision).

**Comment by sdreher** [comment]
@cogat - Thanks for following up. Very appreciated. Yes - as I dug deeper into the specification I saw the 'x' is preferred to determine precision, so went ahead and closed the issue. You can take a look at https://github.com/ccnmtl/footprints to see the larger project I referenced. The ability to use real sortable dates will definitely make the project come to life.
