### ISSUE TITLE
Improve parser performance

### ISSUE THREAD

**Issue by cogat** [ixc/python-edtf#11]
The parser seems to take a while to compile, and another while to parse dates, especially sets of multiple dates.

The EDTF grammar is geared towards exactness rather than speed, meaning that there are strict definitions of numbers which can be used in months, etc.

There might be ways of relaxing the lexical definitions in order to improve parse speed, and then perhaps validating actual values using something simpler after parse time.

**Comment by aweakley** [comment]
This is resolved by #56
