### ISSUE TITLE
New release, please?

### ISSUE THREAD

**Issue by zerebubuth** [ixc/python-edtf#2]
We're using the EDTF library in [our code](https://github.com/mapzen/tilequeue/blob/master/setup.py#L34), thanks very much for making it available!

I noticed that you made [a change](https://github.com/ixc/python-edtf/commit/fffa4d209899853217e38c341e02878bd512f0ce) to avoid dependency problems with potentially importing `dateutil.relativedelta` during the dependency-finding phase of installation. It's something we've [worked around](https://github.com/mapzen/chef-tilequeue/pull/17), and it's also affecting people [using our code](https://github.com/mapzen/vector-datasource/issues/574).

Please could you push a 0.9.2 release up to PyPI which we could explicitly depend on to resolve this issue?

**Comment by mrmachine** [comment]
@zerebubuth thanks for the prod. Sorry this slipped off my radar for so long. I've just published a new package on PyPI.
