### ISSUE TITLE
Fails now on Mac + Python 3.6

### ISSUE THREAD

**Issue by texnic** [ixc/python-edtf#23]
Mac:~ texnic$ virtualenv venv-edtf
Using base prefix '/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6'
New python executable in /Users/texnic/venv-edtf/bin/python3.6
Not overwriting existing python script /Users/texnic/venv-edtf/bin/python (you must use /Users/texnic/venv-edtf/bin/python3.6)
Installing setuptools, pip, wheel...done.

Mac:~ texnic$ source venv-edtf/bin/activate
(venv-edtf) Mac:~ texnic$ pip3 install edtf
Collecting edtf
Collecting python-dateutil (from edtf)
  Using cached python_dateutil-2.6.1-py2.py3-none-any.whl
Collecting pyparsing (from edtf)
  Using cached pyparsing-2.2.0-py2.py3-none-any.whl
Collecting six>=1.5 (from python-dateutil->edtf)
  Using cached six-1.10.0-py2.py3-none-any.whl
Installing collected packages: six, python-dateutil, pyparsing, edtf
Successfully installed edtf-2.6.0 pyparsing-2.2.0 python-dateutil-2.6.1 six-1.10.0

(venv-edtf) Mac:~ texnic$ python3
Python 3.6.2 (default, Jul 17 2017, 16:44:45) 
[GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.42)] on darwin
Type "help", "copyright", "credits" or "license" for more information.

>>> from edtf import parse_edtf
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/texnic/venv-edtf/lib/python3.6/site-packages/edtf/__init__.py", line 1, in <module>
    from parser.grammar import parse_edtf
ModuleNotFoundError: No module named 'parser.grammar'; 'parser' is not a package

**Comment by thewilkybarkid** [comment]
Same problem here on Python 3.5.
