### ISSUE TITLE
Merge fork from saw-leipzig 

### ISSUE THREAD

**Issue by aweakley** [ixc/python-edtf#42]
Currently there's a neglected PR #40 from https://github.com/saw-leipzig/python-edtf/  We very much appreciate the contribution, and I'm sorry I didn't realise that work was happening. That's meant we missed the boat last year and so that fork moved on, renaming things to edtf2. 

The proposal now is to merge that work in to our code, undoing that renaming, in the new [v5](https://github.com/ixc/python-edtf/tree/v5) branch. (After that, under another issue, we'll extend the work to add additional changes to match the 2019 spec, and then release as v5).

As a start I've merged up to 300b4fe8bedbf3d1790dbef23613c95c3aa2bf6a which is the commit immediately before the renaming happened. We'll need to step through subsequent commits carefully to merge in the changes without the rename.

I currently see two test failures where the new code returns `math.inf` or `-math.inf` for `..` dates. I get the same failures from the current [head of the fork](https://github.com/saw-leipzig/python-edtf/commit/6881ea66071399fbe5e4901c51255e6cb81d13fb). So I think it may be best to resolve these after the step-by-step merging is complete.

**Comment by ColeDCrawford** [comment]
I'm not sure what the `parser/parser_classes_tests.py` or `parser/grammar_test.py` files are, but they are not typical tests files. There's a high proportion of overlap with `parser_classes` and `grammar` but it's not 1:1. Both of those files were added in the big namespace change commit: https://github.com/ixc/python-edtf/commit/1e3a01176d981df3ce63b6f8232c80b9f50597e4

**Comment by aweakley** [comment]
This is resolved now.
