### ISSUE TITLE
Add performance tests

### ISSUE THREAD

**Issue by ColeDCrawford** [ixc/python-edtf#50]
PR #36 adds packratting for pyparser to improve performance. I think it would be great to merge in that feature, but also useful to take some benchmarks for before and after. These can be done as part of the CI, though I don't think we necessarily need them to hit specific metrics for the CI to pass.

**Comment by aweakley** [comment]
The benchmark graphs are appearing here now https://ixc.github.io/python-edtf/dev/bench/

**Comment by aweakley** [comment]
This does seem to have made quite a difference in some cases:

![image](https://github.com/ixc/python-edtf/assets/224316/9c059d14-f57d-441c-a7de-712ec98e15c7)
