### ISSUE TITLE
Roadmap to version 5

### ISSUE THREAD

**Issue by rettinghaus** [ixc/python-edtf#74]
It would be nice to have some idea when version 5 could be released. Are there still critical issues to be closed?
If not maybe make a pre-release for more testing?

**Comment by aweakley** [comment]
v5 is released, https://pypi.org/project/edtf/ so I guess we should be looking at 5.1 with the recent changes? 
This is the other change I wanted to include https://github.com/ixc/python-edtf/pull/73

**Comment by aweakley** [comment]
Or perhaps 5.1 now and 5.2 with #73 makes more sense?

**Comment by rettinghaus** [comment]
Ah, I see it has been released on pypi, but it‘s missing a release here on GitHub. Please add at least a 5.0 tag here for keeping track.
IMHO #73 could go into 5.1.
